[book]
authors = ["Itamar Turner-Trauring"]
language = "en"
multilingual = false
src = "src"

[build]
create-missing = false

[preprocessor.index]

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html]
additional-css = ["theme/fonts.css"]
curly-quotes = true