name: unpinned
channels:
  - conda-forge
dependencies:
  - python=3.8
  - cython=0.29.15
  - threadpoolctl=2.1.0
  - c-compiler=1.1.3
  - valgrind=3.15.0
  - rust=1.56.1
  - setuptools-rust=0.12.1
  - pip=21.1.1
